INFO 2019-04-26 08:46:18,365 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17052
INFO 2019-04-26 08:46:18,615 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 2957
INFO 2019-04-26 08:46:59,838 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17050
INFO 2019-04-26 08:47:00,026 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3012
INFO 2019-04-26 08:47:05,919 basehttp 124 "POST /verify/check_code/ HTTP/1.1" 200 25
INFO 2019-04-26 08:47:40,028 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17059
INFO 2019-04-26 08:47:40,232 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3284
ERROR 2019-04-26 08:47:43,642 exception 118 Internal Server Error: /verify/check_code/
Traceback (most recent call last):
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/binbin/Desktop/Fake/verification/views.py", line 37, in post
    raise ValidationError('验证码错误')
django.core.exceptions.ValidationError: ['验证码错误']
ERROR 2019-04-26 08:47:43,678 basehttp 124 "POST /verify/check_code/ HTTP/1.1" 500 16052
INFO 2019-04-26 08:48:12,567 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17059
INFO 2019-04-26 08:48:12,734 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3622
INFO 2019-04-26 08:48:18,607 basehttp 124 "POST /verify/check_code/ HTTP/1.1" 200 25
INFO 2019-04-26 08:49:47,951 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17059
INFO 2019-04-26 08:49:48,257 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3275
INFO 2019-04-26 08:49:54,955 basehttp 124 "POST /verify/check_code/ HTTP/1.1" 200 59
INFO 2019-04-26 08:50:03,471 basehttp 124 "POST /verify/check_code/ HTTP/1.1" 200 25
WARNING 2019-04-26 11:37:14,807 base 93 Not Found: /image_codes/f3b9d72e-77e7-438e-9a4c-91e0be00cb34/
WARNING 2019-04-26 11:37:14,827 basehttp 124 "GET /image_codes/f3b9d72e-77e7-438e-9a4c-91e0be00cb34/ HTTP/1.1" 404 2402
WARNING 2019-04-26 11:37:40,744 base 93 Not Found: /image_codes/b34bde02-37a2-4718-b7e7-2720d7a0ea23/
WARNING 2019-04-26 11:37:40,745 basehttp 124 "GET /image_codes/b34bde02-37a2-4718-b7e7-2720d7a0ea23/ HTTP/1.1" 404 2402
INFO 2019-04-26 11:39:53,574 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17059
INFO 2019-04-26 11:39:53,820 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 2971
INFO 2019-04-26 11:39:55,637 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17059
INFO 2019-04-26 11:39:55,785 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3125
INFO 2019-04-26 11:40:02,730 basehttp 124 "POST /user/check_mobile/ HTTP/1.1" 200 79
INFO 2019-04-26 11:40:06,909 basehttp 124 "POST /user/check_mobile/ HTTP/1.1" 200 79
INFO 2019-04-26 11:40:11,368 basehttp 124 "POST /verify/check_code/ HTTP/1.1" 200 59
INFO 2019-04-26 11:40:31,120 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17035
INFO 2019-04-26 11:40:31,245 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3418
INFO 2019-04-26 11:40:35,105 basehttp 124 "POST /verify/check_code/ HTTP/1.1" 200 59
INFO 2019-04-26 11:40:40,069 basehttp 124 "POST /verify/check_code/ HTTP/1.1" 200 53
INFO 2019-04-26 11:40:49,615 basehttp 124 "POST /verify/check_code/ HTTP/1.1" 200 53
INFO 2019-04-26 11:41:10,115 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17035
INFO 2019-04-26 11:41:10,295 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3144
INFO 2019-04-26 11:41:11,214 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17035
INFO 2019-04-26 11:41:11,842 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3114
INFO 2019-04-26 11:41:15,438 basehttp 124 "POST /verify/check_code/ HTTP/1.1" 200 59
INFO 2019-04-26 11:41:19,689 basehttp 124 "POST /verify/check_code/ HTTP/1.1" 200 59
INFO 2019-04-26 11:41:29,096 basehttp 124 "POST /verify/check_code/ HTTP/1.1" 200 59
INFO 2019-04-26 11:43:46,920 basehttp 124 "GET /verify/get_code/? HTTP/1.1" 200 3158
INFO 2019-04-26 11:43:57,902 basehttp 124 "POST /verify/check_code/ HTTP/1.1" 200 59
INFO 2019-04-26 11:44:05,496 basehttp 124 "POST /verify/check_code/ HTTP/1.1" 200 59
INFO 2019-04-26 11:44:10,758 basehttp 124 "GET /verify/get_code/?? HTTP/1.1" 200 3278
INFO 2019-04-26 11:44:17,769 basehttp 124 "POST /verify/check_code/ HTTP/1.1" 200 59
INFO 2019-04-26 11:44:45,028 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17035
INFO 2019-04-26 11:44:45,190 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3415
INFO 2019-04-26 11:44:46,101 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17035
INFO 2019-04-26 11:44:46,389 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3016
INFO 2019-04-26 11:44:52,661 basehttp 124 "POST /verify/check_code/ HTTP/1.1" 200 59
INFO 2019-04-26 11:44:55,016 basehttp 124 "POST /verify/check_code/ HTTP/1.1" 200 59
INFO 2019-04-26 11:45:36,258 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17035
INFO 2019-04-26 11:45:36,392 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3478
INFO 2019-04-26 11:45:38,065 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17035
INFO 2019-04-26 11:45:38,186 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3218
INFO 2019-04-26 11:45:40,482 basehttp 124 "POST /verify/check_code/ HTTP/1.1" 200 59
INFO 2019-04-26 11:45:42,362 basehttp 124 "POST /verify/check_code/ HTTP/1.1" 200 59
INFO 2019-04-26 11:45:47,146 basehttp 124 "POST /verify/check_code/ HTTP/1.1" 200 97
INFO 2019-04-26 11:47:11,997 basehttp 124 "POST /user/signup/ HTTP/1.1" 200 12381
WARNING 2019-04-26 11:47:12,083 base 94 Method Not Allowed (GET): /verify/check_code/
WARNING 2019-04-26 11:47:12,085 basehttp 124 "GET /verify/check_code/ HTTP/1.1" 405 0
INFO 2019-04-26 11:47:16,482 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17035
INFO 2019-04-26 11:49:44,536 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17035
INFO 2019-04-26 11:49:44,693 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3490
INFO 2019-04-26 12:01:00,417 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17035
INFO 2019-04-26 12:01:00,577 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3151
INFO 2019-04-26 12:01:16,858 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17035
INFO 2019-04-26 12:01:20,017 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17035
INFO 2019-04-26 12:01:20,140 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3636
INFO 2019-04-26 12:01:22,657 basehttp 124 "POST /user/check_username/ HTTP/1.1" 200 27
ERROR 2019-04-26 12:01:25,248 exception 118 Internal Server Error: /user/signup/
Traceback (most recent call last):
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view users.views.SignupView didn't return an HttpResponse object. It returned None instead.
ERROR 2019-04-26 12:01:25,382 basehttp 124 "POST /user/signup/ HTTP/1.1" 500 61870
INFO 2019-04-26 12:03:24,565 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 16863
INFO 2019-04-26 12:03:24,715 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3030
INFO 2019-04-26 12:03:27,542 basehttp 124 "POST /user/check_username/ HTTP/1.1" 200 27
ERROR 2019-04-26 12:03:30,946 exception 118 Internal Server Error: /user/signup/
Traceback (most recent call last):
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view users.views.SignupView didn't return an HttpResponse object. It returned None instead.
ERROR 2019-04-26 12:03:31,125 basehttp 124 "POST /user/signup/ HTTP/1.1" 500 61870
INFO 2019-04-26 12:04:15,796 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 16863
INFO 2019-04-26 12:04:15,950 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3216
INFO 2019-04-26 12:04:17,256 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 16863
INFO 2019-04-26 12:04:17,433 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 2922
INFO 2019-04-26 12:04:20,786 basehttp 124 "POST /user/check_username/ HTTP/1.1" 200 27
INFO 2019-04-26 12:04:22,024 basehttp 124 "POST /user/signup/ HTTP/1.1" 200 16863
INFO 2019-04-26 12:04:22,110 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3366
INFO 2019-04-26 12:04:44,206 basehttp 124 "POST /user/check_username/ HTTP/1.1" 200 27
INFO 2019-04-26 12:04:46,053 basehttp 124 "POST /user/signup/ HTTP/1.1" 200 16863
INFO 2019-04-26 12:04:46,144 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3454
INFO 2019-04-26 12:04:48,304 basehttp 124 "POST /user/check_username/ HTTP/1.1" 200 27
INFO 2019-04-26 12:04:49,599 basehttp 124 "POST /user/signup/ HTTP/1.1" 200 16863
INFO 2019-04-26 12:04:49,683 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3101
INFO 2019-04-26 12:04:51,644 basehttp 124 "POST /user/check_username/ HTTP/1.1" 200 27
INFO 2019-04-26 12:04:52,482 basehttp 124 "POST /user/signup/ HTTP/1.1" 200 16863
INFO 2019-04-26 12:04:52,594 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3280
INFO 2019-04-26 12:05:57,507 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 16863
INFO 2019-04-26 12:05:57,715 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3565
INFO 2019-04-26 12:06:00,175 basehttp 124 "POST /user/check_username/ HTTP/1.1" 200 27
ERROR 2019-04-26 12:06:01,760 exception 118 Internal Server Error: /user/signup/
Traceback (most recent call last):
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/binbin/Desktop/Fake/users/views.py", line 68, in post
    return render(request, locals())
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: {'obj': <FormTable bound=True, valid=False, fields=(username;password;email;mobile)>, 'request': <WSGIRequest: POST '/user/signup/'>, 'self': <users.views.SignupView object at 0x7f42ad5ef978>}
ERROR 2019-04-26 12:06:01,975 basehttp 124 "POST /user/signup/ HTTP/1.1" 500 98106
INFO 2019-04-26 12:10:42,317 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17039
INFO 2019-04-26 12:10:42,434 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3095
INFO 2019-04-26 12:10:45,076 basehttp 124 "POST /user/check_username/ HTTP/1.1" 200 27
ERROR 2019-04-26 12:10:46,222 exception 118 Internal Server Error: /user/signup/
Traceback (most recent call last):
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/binbin/Desktop/Fake/users/views.py", line 68, in post
    return render(request, locals())
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: {'obj': <FormTable bound=True, valid=False, fields=(username;password;email;mobile)>, 'request': <WSGIRequest: POST '/user/signup/'>, 'self': <users.views.SignupView object at 0x7f42ad587f98>}
ERROR 2019-04-26 12:10:46,353 basehttp 124 "POST /user/signup/ HTTP/1.1" 500 98106
INFO 2019-04-26 12:15:38,591 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17069
INFO 2019-04-26 12:15:38,768 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3090
INFO 2019-04-26 12:15:40,541 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17069
INFO 2019-04-26 12:15:40,652 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3456
INFO 2019-04-26 12:15:42,960 basehttp 124 "POST /user/check_username/ HTTP/1.1" 200 27
ERROR 2019-04-26 12:15:44,276 exception 118 Internal Server Error: /user/signup/
Traceback (most recent call last):
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/binbin/Desktop/Fake/users/views.py", line 68, in post
    return render(request, locals())
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: {'obj': <FormTable bound=True, valid=False, fields=(username;password;email;mobile)>, 'request': <WSGIRequest: POST '/user/signup/'>, 'self': <users.views.SignupView object at 0x7f42ad30cdd8>}
ERROR 2019-04-26 12:15:44,445 basehttp 124 "POST /user/signup/ HTTP/1.1" 500 98106
INFO 2019-04-26 12:24:03,238 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17721
INFO 2019-04-26 12:24:03,399 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 2814
INFO 2019-04-26 12:24:09,612 basehttp 124 "POST /user/check_mobile/ HTTP/1.1" 200 79
ERROR 2019-04-26 12:24:11,368 exception 118 Internal Server Error: /user/signup/
Traceback (most recent call last):
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/binbin/Desktop/Fake/users/views.py", line 68, in post
    return render(request, locals())
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: {'obj': <FormTable bound=True, valid=False, fields=(username;password;email;mobile)>, 'request': <WSGIRequest: POST '/user/signup/'>, 'self': <users.views.SignupView object at 0x7f42ad30cac8>}
ERROR 2019-04-26 12:24:11,508 basehttp 124 "POST /user/signup/ HTTP/1.1" 500 98105
INFO 2019-04-26 12:29:08,645 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17728
INFO 2019-04-26 12:29:08,790 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3256
ERROR 2019-04-26 12:29:14,485 exception 118 Internal Server Error: /user/signup/
Traceback (most recent call last):
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/binbin/Desktop/Fake/users/views.py", line 68, in post
    return render(request, locals())
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: {'obj': <FormTable bound=True, valid=False, fields=(username;password;email;mobile)>, 'request': <WSGIRequest: POST '/user/signup/'>, 'self': <users.views.SignupView object at 0x7f42ad5a1748>}
ERROR 2019-04-26 12:29:14,674 basehttp 124 "POST /user/signup/ HTTP/1.1" 500 98105
INFO 2019-04-26 12:30:10,750 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17735
INFO 2019-04-26 12:30:10,987 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3250
ERROR 2019-04-26 12:30:17,690 exception 118 Internal Server Error: /user/signup/
Traceback (most recent call last):
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/binbin/Desktop/Fake/users/views.py", line 68, in post
    return render(request, locals())
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: {'obj': <FormTable bound=True, valid=False, fields=(username;password;email;mobile)>, 'request': <WSGIRequest: POST '/user/signup/'>, 'self': <users.views.SignupView object at 0x7f42ad312f98>}
ERROR 2019-04-26 12:30:17,883 basehttp 124 "POST /user/signup/ HTTP/1.1" 500 98105
INFO 2019-04-26 12:35:45,489 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17723
INFO 2019-04-26 12:35:45,618 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3587
ERROR 2019-04-26 12:35:48,719 exception 118 Internal Server Error: /user/signup/
Traceback (most recent call last):
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/binbin/Desktop/Fake/users/views.py", line 68, in post
    return render(request, locals())
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: {'obj': <FormTable bound=True, valid=False, fields=(username;password;email;mobile)>, 'request': <WSGIRequest: POST '/user/signup/'>, 'self': <users.views.SignupView object at 0x7f42ad319400>}
ERROR 2019-04-26 12:35:48,897 basehttp 124 "POST /user/signup/ HTTP/1.1" 500 98105
INFO 2019-04-26 12:36:01,553 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17723
INFO 2019-04-26 12:36:05,338 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17723
INFO 2019-04-26 12:36:05,504 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3006
ERROR 2019-04-26 12:36:10,020 exception 118 Internal Server Error: /user/signup/
Traceback (most recent call last):
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/binbin/.virtualenvs/v2ex/lib/python3.6/site-packages/django/core/handlers/base.py", line 139, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view users.views.SignupView didn't return an HttpResponse object. It returned None instead.
ERROR 2019-04-26 12:36:10,138 basehttp 124 "POST /user/signup/ HTTP/1.1" 500 61872
INFO 2019-04-26 12:36:39,231 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17723
INFO 2019-04-26 12:36:39,378 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3012
INFO 2019-04-26 12:36:42,999 basehttp 124 "POST /user/signup/ HTTP/1.1" 200 12381
WARNING 2019-04-26 12:36:43,067 base 94 Method Not Allowed (GET): /verify/check_code/
WARNING 2019-04-26 12:36:43,068 basehttp 124 "GET /verify/check_code/ HTTP/1.1" 405 0
INFO 2019-04-26 12:37:03,497 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17723
INFO 2019-04-26 12:39:14,639 basehttp 124 "GET /index/ HTTP/1.1" 200 2
WARNING 2019-04-26 12:39:18,045 base 94 Method Not Allowed (GET): /user/signin/
WARNING 2019-04-26 12:39:18,046 basehttp 124 "GET /user/signin/ HTTP/1.1" 405 0
INFO 2019-04-26 12:39:23,015 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17723
INFO 2019-04-26 12:39:23,198 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3148
INFO 2019-04-26 12:40:16,884 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17722
INFO 2019-04-26 12:40:17,033 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3047
INFO 2019-04-26 12:40:21,032 basehttp 124 "POST /user/signup/ HTTP/1.1" 200 12381
WARNING 2019-04-26 12:40:21,177 base 94 Method Not Allowed (GET): /verify/check_code/
WARNING 2019-04-26 12:40:21,179 basehttp 124 "GET /verify/check_code/ HTTP/1.1" 405 0
INFO 2019-04-26 12:40:25,679 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17722
INFO 2019-04-26 12:43:48,542 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17740
INFO 2019-04-26 12:43:48,672 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3205
INFO 2019-04-26 12:43:51,537 basehttp 124 "POST /user/signup/ HTTP/1.1" 200 12381
WARNING 2019-04-26 12:43:51,655 base 94 Method Not Allowed (GET): /verify/check_code/
WARNING 2019-04-26 12:43:51,657 basehttp 124 "GET /verify/check_code/ HTTP/1.1" 405 0
INFO 2019-04-26 12:43:55,403 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17740
INFO 2019-04-26 12:43:57,091 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17740
INFO 2019-04-26 12:43:57,259 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 2525
INFO 2019-04-26 12:44:39,361 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17747
INFO 2019-04-26 12:44:39,606 basehttp 124 "GET /verify/get_code/ HTTP/1.1" 200 3281
INFO 2019-04-26 12:45:31,432 basehttp 124 "POST /user/signup/ HTTP/1.1" 200 12381
WARNING 2019-04-26 12:45:31,542 base 94 Method Not Allowed (GET): /verify/check_code/
WARNING 2019-04-26 12:45:31,544 basehttp 124 "GET /verify/check_code/ HTTP/1.1" 405 0
INFO 2019-04-26 12:45:36,332 basehttp 124 "GET /user/signup/ HTTP/1.1" 200 17747
